apiVersion: v1
kind: Service
metadata:
  name: chaininsight-frontend
  namespace: chaininsight
  labels:
    app.kubernetes.io/name: chaininsight
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: chaininsight
    app.kubernetes.io/component: frontend
