apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaininsight.fullname" . }}-backend
  labels:
    {{- include "chaininsight.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chaininsight.backendSelectorLabels" . | nindent 4 }}
