apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaininsight.fullname" . }}-secret
  labels:
    {{- include "chaininsight.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
